### ISSUE TITLE
CDN Not Found

### ISSUE THREAD

**Issue by Nydigorith** [tomtom-international/maps-sdk-for-web-examples#1]
CDN list below cant be found
GET /cdn.web-sdk-plugin-searchbox/SearchBox.css
GET /cdn.web-sdk-maps/maps-web.min.js
GET /cdn.web-sdk-maps/maps.css
GET /cdn.web-sdk-services/services-web.min.js
GET /cdn.web-sdk-plugin-searchbox/SearchBox-web.js
GET /cdn.web-sdk-services/services-web.min.js
GET /cdn.web-sdk-plugin-searchbox/SearchBox-web.js

**Comment by KarolBlaszczyk-TomTom** [comment]
Hi, 

Please go through README file, you need to run scripts to replace these placeholders (and also, keys).
