### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by natemate90** [tomtom-international/maps-sdk-for-web-examples#3]
Hi, 

According to Snyk.io, there are indirect security issues in your package (presumably peer dependencies). Is there any chance that tomtom will fix this soon?

See
https://snyk.io/advisor/npm-package/@tomtom-international/web-sdk-services
https://snyk.io/test/npm/%40tomtom-international/web-sdk-maps/6.15.0

**Comment by natemate90** [comment]
The easiest way to resolve is to upgrade your peer dependencies. This is effortless.

- Upgrade to axios@0.21.3
- Upgrade to lodash@4.17.21
- Upgrade to node-fetch@2.6.7

**Comment by EduardoMarques-TomTom** [comment]
Hi,

thanks for that. 

We are on it, we will audit the dependencies of these packages and update them.

**Comment by stanislawpuda-tomtom** [comment]
Hi,

we released 6.18.0 version of our SDK, where vulnerable dependencies were updated (or removed).
