### ISSUE TITLE
minimist version has Prototype Pollution vulnerability

### ISSUE THREAD

**Issue by inikimzk** [tomtom-international/maps-sdk-for-web-examples#4]
the current version of minimist that comes with the mapbox-gl dependency of the tomtom-international/maps-sdk-for-web has a Prototype Pollution vulnerability. When mapbox-gl upgrades to a newer version of minimist, can you please upgrade to that newer version of mapbox-gl? Thank you!

**Comment by zbigniewmatysek-tomtom** [comment]
We have released new version (6.19.0) fixing this issue. Updating mapbox-gl didn't solve the issue, but we managed to override minimist via package-lock.

Thank you for reporting this.
